### ISSUE TITLE
Updated volumedriver on system but startup fails due to backward compat issue in serialization code

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/volumedriver#112]
@redlicha: pls update with additional details after further debugging - thx

**Comment by redlicha** [comment]
update:  6.0.4-dev.201609060030.7a8da55 -> 6.0.4-dev.201609090836.125f7e5
deserialization of `ClusterNodeConfig` throws an exception:
```
Catchpoint 1 (exception thrown), 0x00007ffff297d9f0 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff297d9f0 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004c50f4 in boost::serialization::throw_exception<boost::archive::archive_exception> (e=...) at /usr/include/boost/serialization/throw_exception.hpp:36
#2  0x000000000050c8bf in load<boost::archive::tracking_type> (this=<optimized out>, t=...) at /usr/include/boost/archive/basic_text_iprimitive.hpp:86
#3  load<boost::archive::tracking_type> (t=..., this=<optimized out>) at /usr/include/boost/archive/text_iarchive.hpp:63
#4  load_primitive<boost::archive::text_iarchive, boost::archive::tracking_type> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:103
#5  invoke<boost::archive::tracking_type> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:385
#6  invoke<boost::archive::tracking_type> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:462
#7  load<boost::archive::text_iarchive, boost::archive::tracking_type> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:618
#8  load_override<boost::archive::tracking_type> (t=..., this=<optimized out>) at /usr/include/boost/archive/detail/common_iarchive.hpp:66
#9  load_override<boost::archive::tracking_type> (t=..., this=<optimized out>) at /usr/include/boost/archive/basic_text_iarchive.hpp:71
#10 load_override<boost::archive::tracking_type> (t=..., this=<optimized out>) at /usr/include/boost/archive/text_iarchive.hpp:92
#11 operator>><boost::archive::tracking_type> (t=..., this=<optimized out>) at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#12 boost::archive::detail::common_iarchive<boost::archive::text_iarchive>::vload (this=<optimized out>, t=...)
    at /usr/include/boost/archive/detail/common_iarchive.hpp:57
#13 0x00007ffff4b5a2f9 in boost::archive::detail::basic_iarchive_impl::load_preamble(boost::archive::detail::basic_iarchive&, boost::archive::detail::basic_iarchive_impl::cobject_id&) () from /usr/lib/libboost_serialization.so.1.57.0
#14 0x00007ffff4b5a9c6 in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) ()
   from /usr/lib/libboost_serialization.so.1.57.0
#15 0x000000000066036e in invoke<volumedriverfs::MessagePort> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:410
#16 invoke<volumedriverfs::MessagePort> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:462
#17 load<boost::archive::text_iarchive, volumedriverfs::MessagePort> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:618
#18 load_override<volumedriverfs::MessagePort> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/common_iarchive.hpp:66
#19 load_override<volumedriverfs::MessagePort> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/basic_text_iarchive.hpp:71
#20 load_override<volumedriverfs::MessagePort> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/text_iarchive.hpp:92
#21 operator>><volumedriverfs::MessagePort> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#22 operator&<volumedriverfs::MessagePort> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/interface_iarchive.hpp:67
#23 volumedriverfs::ClusterNodeConfig::load<boost::archive::text_iarchive> (this=0x7fffffffc2a8, ar=..., version=1)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/ClusterNodeConfig.h:117
#24 0x00007ffff4b5aa36 in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) ()
   from /usr/lib/libboost_serialization.so.1.57.0
#25 0x000000000065f847 in invoke<volumedriverfs::ClusterNodeConfig> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:410
#26 invoke<volumedriverfs::ClusterNodeConfig> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:462
#27 load<boost::archive::text_iarchive, volumedriverfs::ClusterNodeConfig> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:618
#28 load_override<volumedriverfs::ClusterNodeConfig> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/common_iarchive.hpp:66
#29 load_override<volumedriverfs::ClusterNodeConfig> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/basic_text_iarchive.hpp:71
#30 load_override<volumedriverfs::ClusterNodeConfig> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/text_iarchive.hpp:92
#31 operator>><volumedriverfs::ClusterNodeConfig> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#32 operator&<volumedriverfs::ClusterNodeConfig> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/interface_iarchive.hpp:67
#33 serialize<boost::archive::text_iarchive> (version=<optimized out>, ar=..., this=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/ClusterNodeStatus.h:83
#34 serialize<boost::archive::text_iarchive, volumedriverfs::ClusterNodeStatus> (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/access.hpp:118
#35 serialize<boost::archive::text_iarchive, volumedriverfs::ClusterNodeStatus> (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/serialization.hpp:69
#36 serialize_adl<boost::archive::text_iarchive, volumedriverfs::ClusterNodeStatus> (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/serialization.hpp:128
#37 boost::archive::detail::iserializer<boost::archive::text_iarchive, volumedriverfs::ClusterNodeStatus>::load_object_data (this=<optimized out>, ar=..., 
    x=0x7fffffffc2a8, file_version=<optimized out>) at /usr/include/boost/archive/detail/iserializer.hpp:184
#38 0x00007ffff4b5aa36 in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) ()
   from /usr/lib/libboost_serialization.so.1.57.0
#39 0x000000000065f2f5 in invoke<volumedriverfs::ClusterNodeStatus> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:410
#40 invoke<volumedriverfs::ClusterNodeStatus> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:462
#41 load<boost::archive::text_iarchive, volumedriverfs::ClusterNodeStatus> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:618
#42 load_override<volumedriverfs::ClusterNodeStatus> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/common_iarchive.hpp:66
---Type <return> to continue, or q <return> to quit---
#43 load_override<volumedriverfs::ClusterNodeStatus> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/basic_text_iarchive.hpp:71
#44 load_override<volumedriverfs::ClusterNodeStatus> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/text_iarchive.hpp:92
#45 operator>><volumedriverfs::ClusterNodeStatus> (t=..., this=0x7fffffffc440) at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#46 load<boost::archive::text_iarchive> (ar=..., this=<optimized out>) at /usr/include/boost/serialization/nvp.hpp:83
#47 member_load<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/access.hpp:101
#48 invoke (file_version=<optimized out>, t=..., ar=...) at /usr/include/boost/serialization/split_member.hpp:54
#49 split_member<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/split_member.hpp:69
#50 serialize<boost::archive::text_iarchive> (file_version=<optimized out>, ar=..., this=<optimized out>) at /usr/include/boost/serialization/nvp.hpp:85
#51 serialize<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/access.hpp:118
#52 serialize<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (file_version=<optimized out>, t=..., ar=...)
    at /usr/include/boost/serialization/serialization.hpp:69
#53 serialize_adl<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (file_version=0, t=..., ar=...)
    at /usr/include/boost/serialization/serialization.hpp:128
#54 invoke<boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> > (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:396
#55 invoke<boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> const> (t=..., ar=...) at /usr/include/boost/archive/detail/iserializer.hpp:462
#56 load<boost::archive::text_iarchive, boost::serialization::nvp<volumedriverfs::ClusterNodeStatus> const> (t=..., ar=...)
    at /usr/include/boost/archive/detail/iserializer.hpp:618
    at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#61 load_construct_data<boost::archive::text_iarchive> (version=0, pair=0x7fffffffc2a0, ar=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/ClusterRegistry.h:165
#62 load_construct_data_adl<boost::archive::text_iarchive, std::pair<volumedriverfs::NodeId const, volumedriverfs::ClusterNodeStatus> > (file_version=0, 
    t=0x7fffffffc2a0, ar=...) at /usr/include/boost/serialization/serialization.hpp:158
#63 stack_construct (version=0, ar=..., this=0x7fffffffc2a0) at /usr/include/boost/serialization/detail/stack_constructor.hpp:54
#64 operator() (this=<optimized out>, hint=..., v=0, s=std::map with 0 elements, ar=...) at /usr/include/boost/serialization/collections_load_imp.hpp:83
#65 boost::serialization::stl::load_collection<boost::archive::text_iarchive, std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus, std::less<volumedriverfs::NodeId>, std::allocator<std::pair<volumedriverfs::NodeId const, volumedriverfs::ClusterNodeStatus> > >, boost::serialization::stl::archive_input_map<boost::archive::text_iarchive, std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus, std::less<volumedriverfs::NodeId>, std::allocator<std::pair<volumedriverfs::NodeId const, volumedriverfs::ClusterNodeStatus> > > >, boost::serialization::stl::no_reserve_imp<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus, std::less<volumedriverfs::NodeId>, std::allocator<std::pair<volumedriverfs::NodeId const, volumedriverfs::ClusterNodeStatus> > > > > (ar=..., s=std::map with 0 elements)
    at /usr/include/boost/serialization/collections_load_imp.hpp:158
#66 0x00007ffff4b5aa36 in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) ()
   from /usr/lib/libboost_serialization.so.1.57.0
Python Exception <class 'ValueError'> Cannot find type const std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus, std::less<volumedriverfs::NodeId>, std::allocator<std::pair<volumedriverfs::NodeId const, volumedriverfs::ClusterNodeStatus> > >::_Rep_type: 
#67 0x000000000065aeb4 in invoke<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, ar=...)
    at /usr/include/boost/archive/detail/iserializer.hpp:410
#68 invoke<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, ar=...)
    at /usr/include/boost/archive/detail/iserializer.hpp:462
#69 load<boost::archive::text_iarchive, std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, ar=...)
    at /usr/include/boost/archive/detail/iserializer.hpp:618
#70 load_override<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, this=0x7fffffffc440)
    at /usr/include/boost/archive/detail/common_iarchive.hpp:66
#71 load_override<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, this=0x7fffffffc440)
    at /usr/include/boost/archive/basic_text_iarchive.hpp:71
#72 load_override<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, this=0x7fffffffc440)
    at /usr/include/boost/archive/text_iarchive.hpp:92
#73 operator>><std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (t=std::map with 0 elements, this=0x7fffffffc440)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/boost/archive/detail/interface_iarchive.hpp:60
#74 operator() (__closure=<optimized out>, is=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/ClusterRegistry.cpp:70
#75 std::_Function_handler<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus, std::less<volumedriverfs::NodeId>, std::allocator<std::pair<const volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > >(std::basic_istream<char, std::char_traits<char> >&), volumedriverfs::(anonymous namespace)::deserialize_node_map(const arakoon::buffer&)::<lambda(std::istream&)> >::_M_invoke(const std::_Any_data &, std::basic_istream<char, std::char_traits<char> > &) (__functor=..., __args#0=...)
    at /usr/include/c++/4.9/functional:2025
#76 0x000000000065a21a in operator() (__args#0=..., this=0x7fffffffc580) at /usr/include/c++/4.9/functional:2439
#77 as_istream<std::map<volumedriverfs::NodeId, volumedriverfs::ClusterNodeStatus> > (fun=..., this=0x7fffffffc530)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/../youtils/ArakoonInterface.h:224
#78 deserialize_node_map (buf=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/ClusterRegistry.cpp:72
#79 volumedriverfs::ClusterRegistry::get_node_status_map (this=0x1275600)
[...]
```

**Comment by redlicha** [comment]
Verified by testing manually on the env where the issue was originally observed.
