### ISSUE TITLE
Segfault in Xio/RDMA server

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#140]
```
(gdb) bt
#0  0x00007f7383de1070 in ?? ()
#1  0x00007f74acf2d927 in xio_nexus_on_send_msg_comp (task=0x7f73835a42e0, nexus=0x7f7381fa45f0) at ../common/xio_nexus.c:899
#2  xio_nexus_on_send_completion (event_data=<optimized out>, event_data=<optimized out>, nexus=0x7f7381fa45f0) at ../common/xio_nexus.c:1501
#3  xio_nexus_on_transport_event (observer=0x7f7381fa45f0, sender=<optimized out>, event=<optimized out>, event_data=0x7f739a7f8a10) at ../common/xio_nexus.c:1631
#4  0x00007f74acf2ab80 in xio_observable_notify_all_observers (observable=observable@entry=0x7f7382ab6010, event=event@entry=6, event_data=event_data@entry=0x7f739a7f8a10) at ../common/xio_observer.c:234
#5  0x00007f74acf108fb in xio_transport_notify_observer (event_data=0x7f739a7f8a10, event=6, trans_hndl=0x7f7382ab6010) at ../../src/common/xio_transport.h:303
#6  xio_rdma_on_rsp_send_comp (task=0x7f73835a42e0, rdma_hndl=0x7f7382ab6010) at transport/rdma/xio_rdma_datapath.c:2802
#7  xio_rdma_tx_comp_handler (task=0x7f73835a42e0, rdma_hndl=0x7f7382ab6010) at transport/rdma/xio_rdma_datapath.c:885
#8  xio_handle_wc (wc=0x7f7380012050, wc=0x7f7380012050, last_in_rxq=0) at transport/rdma/xio_rdma_datapath.c:1117
#9  xio_poll_cq (tcq=tcq@entry=0x7f738000f4a0, timeout_us=0, max_wc=128) at transport/rdma/xio_rdma_datapath.c:1216
#10 0x00007f74acf131dc in xio_poll_cq_armable (tcq=0x7f738000f4a0) at transport/rdma/xio_rdma_datapath.c:1263
#11 0x00007f74acf132d5 in xio_cq_event_handler (fd=<optimized out>, events=<optimized out>, data=0x7f738000f4a0) at transport/rdma/xio_rdma_datapath.c:1363
#12 0x00007f74acefbfe0 in xio_ev_loop_run_helper (loop_hndl=0x7f7380009ab0, timeout=-1) at xio/xio_ev_loop.c:448
#13 0x00007f74acefe735 in xio_context_run_loop (ctx=0x7f73800098a0, timeout_ms=<optimized out>) at xio/xio_context.c:503
#14 0x000000000056b63c in volumedriverfs::NetworkXioServer::run (this=0x1740ed8, promise=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/NetworkXioServer.cpp:302
#15 0x000000000056dfc8 in volumedriverfs::NetworkXioInterface::run (this=<optimized out>, promise=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/NetworkXioInterface.cpp:38
#16 0x0000000000532644 in operator() (__closure=<optimized out>) at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/FuseInterface.cpp:357
#17 boost::detail::thread_data<volumedriverfs::FuseInterface::operator()(const boost::filesystem::path&, const std::vector<std::basic_string<char> >&)::<lambda()> >::run(void) (this=<optimized out>)
    at /usr/include/boost/thread/detail/thread.hpp:116
#18 0x00007f74aa56d42a in ?? () from /usr/lib/libboost_thread.so.1.57.0
#19 0x00007f74acce0182 in start_thread (arg=0x7f739a7fc700) at pthread_create.c:312
#20 0x00007f74a78e147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by redlicha** [comment]
There are keepalive timeout messages in the logs:
```
/var/log/upstart/ovs-volumedriver_data01.log:[2016/10/11-16:43:08.132145] xio_connection.c:3261        [ERROR] - connection keepalive timeout. connection:0x7fe95c027710 probes:[3]
```
There's however no trivial correlation with the crashes - there might be multiple of these before a segfault, and a segfault is typically not immediately preceded by such a message.

**Comment by redlicha** [comment]
Another observation (also without a trivial correlation to the segfaults): dmesg contains a big number of these messages:
```
Tue Oct 11 22:39:27 2016] mlx4_core 0000:04:00.1: mlx4_dec_port_macs removed mac, port: 1, now: 47
[Tue Oct 11 23:09:20 2016] mlx4_core 0000:04:00.1: mlx4_inc_port_macs added mac for port: 1, now: 48
[Tue Oct 11 23:09:42 2016] mlx4_core 0000:04:00.1: mlx4_dec_port_macs removed mac, port: 1, now: 47
[Tue Oct 11 23:09:42 2016] mlx4_core 0000:04:00.1: mlx4_inc_port_macs added mac for port: 1, now: 48
[Tue Oct 11 23:09:42 2016] mlx4_core 0000:04:00.1: mlx4_inc_port_macs added mac for port: 1, now: 49
[Tue Oct 11 23:09:43 2016] mlx4_core 0000:04:00.1: mlx4_dec_port_macs removed mac, port: 1, now: 48
[Tue Oct 11 23:09:43 2016] mlx4_core 0000:04:00.1: mlx4_inc_port_macs added mac for port: 1, now: 49
[Tue Oct 11 23:09:48 2016] mlx4_core 0000:04:00.1: mlx4_dec_port_macs removed mac, port: 1, now: 48
[Tue Oct 11 23:09:48 2016] mlx4_core 0000:04:00.1: mlx4_dec_port_macs removed mac, port: 1, now: 47
[Tue Oct 11 23:39:20 2016] mlx4_core 0000:04:00.1: mlx4_inc_port_macs added mac for port: 1, now: 48
```

**Comment by redlicha** [comment]
Very likely related to the network configuration of the env where this was observed - after changing the switches' MLAG configuration the crash / errors on the client side were not reproducible anymore.

**Comment by wimpers** [comment]
After discussion with @redlicha set to verification for QA .

**Comment by saelbrec** [comment]
At the same time of the network reconfiguration to remove the MLAG, we also updated the volumedriver bits to version 6.2.0-dev.201610111739.214ae77 which included https://github.com/openvstorage/volumedriver/commit/214ae77d2069a6e22b7e88a3bbf9964a89f3e1cd and the XIO KEEPALIVE settings were changed to the Mellanox defaults(timeout=60, interval=20 and probes=3)
So those changes could also have had a positive effect on stability.

**Comment by wimpers** [comment]
Closed by PM.
