### ISSUE TITLE
Set as template should not be possible when volume has children

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#163]
```
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 641892 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/XMLRPCTimingWrapper - 000000000000314f - info - execute: Arguments for unlink are {[target_path:/vdisk-clone.raw,vrouter_cl
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 641896 +0100 - Ubuntu-16-04 - 16914/0x00007f827d7fa700 - volumedriverfs/MTServer - 000000000000314e - info - cleanup_threads_locked: Trying to join 2 threads
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 645434 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/LockedArakoon - 0000000000003150 - info - run_sequence: set entry succeeded after 1 attempt(s)
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 645504 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/VFSObjectRouter - 0000000000003151 - info - unlink: 3024b57b-6809-4178-a3b0-f2b214501cca
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 645551 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/VFSLocalNode - 0000000000003152 - info - unlink: 3024b57b-6809-4178-a3b0-f2b214501cca: deleting object
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 645721 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/ObjectRegistry - 0000000000003153 - info - unregister: d60f552b-ab7e-4f32-be3f-616db74b4f77/veepoeluiwzBUYjlSGW7G8F: unregi
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 646098 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/ObjectRegistry - 0000000000003154 - error - do_prepare_unregister_volumoid_: Parent 905f66d5-4d80-4a21-9ba5-3e85fc65be96 do
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 646202 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/XMLRPCTimingWrapper - 0000000000003155 - error - execute: unlink Throw location unknown (consider using BOOST_THROW_EXCEPTI
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: Dynamic exception type: volumedriverfs::ConflictingUpdateException
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: std::exception::what: std::exception
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: [volumedriverfs::tag_volume_id*] = 3024b57b-6809-4178-a3b0-f2b214501cca
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: [volumedriverfs::tag_parent_volume_id*] = 905f66d5-4d80-4a21-9ba5-3e85fc65be96
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: [volumedriverfs::tag_desc*] = parent does not refer to clone anymore
Oct 31 14:39:13 Ubuntu-16-04 volumedriver_fs.sh[16914]: 2016-10-31 14:39:13 646321 +0100 - Ubuntu-16-04 - 16914/0x00007f824e330700 - volumedriverfs/XMLRPCConnection - 0000000000003156 - info - operator(): Closing socket 64
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]: 2016-10-31 14:39:13 65100 +0100 - Ubuntu-16-04 - 15328/139987930371840 - celery/celery.worker.job - 54 - ERROR - Task ovs.vdisk.delete[2364f74a-9a20-4f41-a8c5-728925657119] raised unexpected: RuntimeError('got fault response un
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]: Traceback (most recent call last):
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:     R = retval = fun(*args, **kwargs)
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:     return self.run(*args, **kwargs)
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 126, in delete
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]:     vdisk.storagedriver_client.unlink(str(vdisk.devicename))
Oct 31 14:39:13 Ubuntu-16-04 celery[15328]: RuntimeError: got fault response unlink
```

This error was witnessed in following situation:

1. Create vDisk
2. Clone the vDisk
3. Convert the original vDisk into template
4. Delete the clone --> above error

From the framework side, we now block the option to convert a volume into a template if clones are present, but the volumedriver should do the same

PS: Should we apply the same checks for rollback?  Rolling back a volume with clones should be possible?

**Comment by redlicha** [comment]
Rolling back a volume with clones should *not* be possible. VolumeDriver protects itself against this and - as pointed out - also should have protected itself against converting a volume with descendants to a template.
@wimpers, since this can lead to orphaned clones I think 'SRP' is in order.

**Comment by redlicha** [comment]
Test: `volumedriver_fs_test, VolumeTest.no_template_creation_if_clones_are_present`
