### ISSUE TITLE
Local volume restart reads too many TLogs

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#217]
The volumes under test have not been written to but accumulated a number of (empty) TLogs due to automated snapshotting.

`SnapshotManagement::getLastSCOInBackend` walks over the TLogs backwards to find the last clusterlocation (with the aim of eventually identifying the last one on the backend). Together with a slow backend (due to disqualified ASDs) this *considerably* delays volume restarts.

```
(gdb) bt
#0  0x00007f927e14f153 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000609bed in boost::asio::detail::epoll_reactor::run (this=0x6b9066e0, block=block@entry=true, ops=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x0000000000bd9c83 in boost::asio::detail::task_io_service::do_run_one (this=0x27dbb80, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:356
#3  0x0000000000bd7db9 in boost::asio::detail::task_io_service::run_one (ec=..., this=0x27dbb80) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:170
#4  boost::asio::io_service::run_one (this=<optimized out>) at /usr/include/boost/asio/impl/io_service.ipp:72
#5  0x0000000000bdb4d1 in boost::asio::basic_socket_streambuf<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp>, boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >::underflow (this=0x6b9a4050) at /usr/include/boost/asio/basic_socket_streambuf.hpp:318
#6  0x00007f927ea4dfed in std::basic_streambuf<char, std::char_traits<char> >::xsgetn(char*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f927ea278eb in std::istream::read(char*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x0000000000bd786e in alba::llio::message::message (is=..., this=0x7ffce2b07230)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/alba.git/cpp/automake_client/../include/llio.h:72
#9  alba::proxy_client::TCPProxy_client::_input (this=0x6b9a4000) at ../src/lib/tcp_proxy_client.cc:67
#10 0x0000000000be12e8 in alba::proxy_client::GenericProxy_client::read_object_fs (this=0x6b9a4000, namespace_="29bff6f4-b959-4584-ae8a-448cb2a7e777", object_name="tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761", 
    dest_file="/mnt/ssd3/data01_db_tlog_1/29bff6f4-b959-4584-ae8a-448cb2a7e777/tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761_temporaryFxU6GL3iyG6u", consistent_read=<optimized out>, should_cache=<optimized out>)
    at ../src/lib/generic_proxy_client.cc:142
#11 0x0000000000af3974 in backend::albaconn::Connection::<lambda()>::operator() (__closure=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:312
#12 backend::albaconn::Connection::convert_exceptions_<void, backend::albaconn::Connection::read_(const backend::Namespace&, const boost::filesystem::path&, const string&, InsistOnLatestVersion)::<lambda()> > (
    desc=0xe19d4a "read object", this=0x52b77b10, fun=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:185
#13 backend::albaconn::Connection::read_ (this=0x52b77b10, nspace=..., dst=..., name="tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761", insist_on_latest_version=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:313
#14 0x0000000000aa7aee in backend::BackendConnectionInterface::read (this=0x52b77b10, nspace=..., destination=..., name="tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761", 
    insist_on_latest=insist_on_latest@entry=InsistOnLatestVersion::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendConnectionInterface.cpp:198
#15 0x0000000000ab0f3b in backend::BackendInterface::do_wrap_<backend::(anonymous namespace)::NamespaceConnFetcher, void, backend::Namespace const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, InsistOnLatestVersion> (get_conn=<synthetic pointer>, mem_fun=<optimized out>, params=..., this=0x9e314340)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:81
#16 backend::BackendInterface::wrap_<void, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, InsistOnLatestVersion> (mem_fun=<optimized out>, 
    params=..., this=0x9e314340) at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:174
#17 backend::BackendInterface::<lambda(InsistOnLatestVersion)>::operator() (insist=InsistOnLatestVersion::F, __closure=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:247
#18 std::_Function_handler<void(InsistOnLatestVersion), backend::BackendInterface::read(const boost::filesystem::path&, const string&, InsistOnLatestVersion, const backend::BackendRequestParameters&)::<lambda(InsistOnLatestVersion)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/lib/debug/usr/bin/volumedriver_fs, CU 0x5f5ed71, DIE 0x5ffae0e>) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/5/functional:1871
#19 0x0000000000ab3497 in std::function<void (InsistOnLatestVersion)>::operator()(InsistOnLatestVersion) const (__args#0=InsistOnLatestVersion::F, this=0x7ffce2b07880) at /usr/include/c++/5/functional:2267
#20 backend::BackendInterface::handle_eventual_consistency_<void>(InsistOnLatestVersion, std::function<void (InsistOnLatestVersion)>&&) (this=this@entry=0x9e314340, 
    insist_on_latest=insist_on_latest@entry=InsistOnLatestVersion::F, fun=fun@entry=<unknown type in /usr/lib/debug/usr/bin/volumedriver_fs, CU 0x5f5ed71, DIE 0x5fdcbe4>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:198
#21 0x0000000000aa9e02 in backend::BackendInterface::read (this=<optimized out>, dst=..., name="tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761", insist_on_latest=insist_on_latest@entry=InsistOnLatestVersion::F, params=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:251
#22 0x00000000009ce406 in volumedriver::OneFileTLogReader::OneFileTLogReader (this=0x9af078c0, TLogPath=..., TLogName="tlog_d8e9053b-d4dc-4968-9b88-1c23496b9761", 
    bi=std::unique_ptr<backend::BackendInterface> containing 0x7ffce2b07e20)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/OneFileTLogReader.cpp:46
#23 0x00000000008c9248 in volumedriver::BackwardTLogReader::BackwardTLogReader (this=0x9af078c0, TLogPath=..., TLogName=..., bi=..., cache_size=65536)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/BackwardTLogReader.cpp:33
#24 0x0000000000877231 in volumedriver::TLogReaderGen<volumedriver::BackwardTLogReader, std::vector<volumedriver::TLogId, std::allocator<volumedriver::TLogId> > >::update (this=0x94ea7d40)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/CombinedTLogReader.h:85
#25 0x000000000086ebc2 in volumedriver::CombinedTLogReader::nextAny (this=0x26d8450)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/CombinedTLogReader.h:132
#26 0x0000000000a12413 in volumedriver::TLogReaderInterface::nextLocation (this=0x26d8450)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/TLogReaderInterface.cpp:80
#27 0x0000000000a12470 in volumedriver::TLogReaderInterface::nextClusterLocation (this=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/TLogReaderInterface.cpp:71
#28 0x00000000009facde in volumedriver::SnapshotManagement::getLastSCOInBackend (this=0x9888bfe0)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/SnapshotManagement.cpp:1095
#29 0x000000000086b68f in volumedriver::Volume::localRestart (this=this@entry=0x9e317900)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/Volume.cpp:465
#30 0x00000000008a1026 in volumedriver::VolumeFactory::local_restart_volume (config=..., owner_tag=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolumeFactory.cpp:636
#31 0x00000000008a2f75 in volumedriver::VolumeFactory::local_restart (config=..., owner_tag=..., fallback=<optimized out>, ignore_foc=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolumeFactory.cpp:689
#32 0x00000000007e3d00 in volumedriver::VolManager::<lambda(const backend::Namespace&, const volumedriver::VolumeConfig&)>::operator() (cfg=..., __closure=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolManager.cpp:1154
#33 std::_Function_handler<std::shared_ptr<volumedriver::Volume>(const backend::Namespace&, const volumedriver::VolumeConfig&), volumedriver::VolManager::local_restart(const backend::Namespace&, volumedriver::OwnerTag, volumedriver::FallBackToBackendRestart, volumedriver::IgnoreFOCIfUnreachable)::<lambda(const backend::Namespace&, const volumedriver::VolumeConfig&)> >::_M_invoke(const std::_Any_data &, const backend::Namespace &, const volumedriver::VolumeConfig &) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/5/functional:1857
#34 0x000000000081c065 in std::function<std::shared_ptr<volumedriver::Volume> (backend::Namespace const&, volumedriver::VolumeConfig const&)>::operator()(backend::Namespace const&, volumedriver::VolumeConfig const&) const
    (__args#1=..., __args#0=..., this=0x7ffce2b090b0) at /usr/include/c++/5/functional:2267
#35 volumedriver::VolManager::with_restart_map_and_unlocked_mgmt_<std::shared_ptr<volumedriver::Volume> >(std::function<std::shared_ptr<volumedriver::Volume> (backend::Namespace const&, volumedriver::VolumeConfig const&)> const&, backend::Namespace const&, volumedriver::VolumeConfig const&) (this=this@entry=0x27dc800, fun=..., ns=..., cfg=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolManager.cpp:819
#36 0x00000000007f3559 in volumedriver::VolManager::with_restart_map_and_unlocked_mgmt_vol_(std::function<std::shared_ptr<volumedriver::Volume> (backend::Namespace const&, volumedriver::VolumeConfig const&)> const&, backend::Namespace const&, volumedriver::VolumeConfig const&) (this=this@entry=0x27dc800, fun=..., ns=..., cfg=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolManager.cpp:828
#37 0x00000000007f4e97 in volumedriver::VolManager::local_restart (this=0x27dc800, ns=..., owner_tag=..., fallback=fallback@entry=volumedriver::FallBackToBackendRestart::T, 
    ignoreFOCIfUnreachable=ignoreFOCIfUnreachable@entry=volumedriver::IgnoreFOCIfUnreachable::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolManager.cpp:1162
#38 0x000000000076a225 in api::local_restart (ns=..., owner_tag=..., fallback=fallback@entry=volumedriver::FallBackToBackendRestart::T, 
    ignoreFOCIfUnreachable=ignoreFOCIfUnreachable@entry=volumedriver::IgnoreFOCIfUnreachable::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/volumedriver/Api.cpp:270
#39 0x00000000006c5126 in volumedriverfs::LocalNode::local_restart_volume_ (this=this@entry=0x2708fd0, reg=..., force=force@entry=volumedriverfs::ForceRestart::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/LocalNode.cpp:1083
#40 0x00000000006c9510 in volumedriverfs::LocalNode::local_restart (this=0x2708fd0, reg=..., force=force@entry=volumedriverfs::ForceRestart::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/LocalNode.cpp:1119
#41 0x0000000000582589 in volumedriverfs::ObjectRouter::maybe_restart (this=0x7ffce2b0a660, id=..., force=force@entry=volumedriverfs::ForceRestart::F)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/ObjectRouter.cpp:1607
#42 0x00000000004bd500 in volumedriverfs::FileSystem::<lambda(const volumedriverfs::FrontendPath&, volumedriverfs::DirectoryEntryPtr)>::operator() (dentry=..., p=..., __closure=0x7ffce2b09980)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/FileSystem.cpp:408
#43 std::_Function_handler<void(const volumedriverfs::FrontendPath&, boost::shared_ptr<volumedriverfs::DirectoryEntry>), volumedriverfs::FileSystem::restart_()::<lambda(const volumedriverfs::FrontendPath&, volumedriverfs::DirectoryEntryPtr)> >::_M_invoke(const std::_Any_data &, const volumedriverfs::FrontendPath &, <unknown type in /usr/lib/debug/usr/bin/volumedriver_fs, CU 0x10a4ca, DIE 0x291c2f>) (__functor=..., __args#0=..., 
    __args#1=<optimized out>) at /usr/include/c++/5/functional:1871
#44 0x0000000000565d04 in std::function<void (volumedriverfs::FrontendPath const&, boost::shared_ptr<volumedriverfs::DirectoryEntry>)>::operator()(volumedriverfs::FrontendPath const&, boost::shared_ptr<volumedriverfs::DirectoryEntry>) const (__args#1=..., __args#0=..., this=0x7ffce2b09980) at /usr/include/c++/5/functional:2267
#45 volumedriverfs::MetaDataStore::walk(volumedriverfs::FrontendPath const&, std::function<void (volumedriverfs::FrontendPath const&, boost::shared_ptr<volumedriverfs::DirectoryEntry>)>&&) (this=this@entry=0x7ffce2b0a948, 
    path=..., fun=fun@entry=<unknown type in /usr/lib/debug/usr/bin/volumedriver_fs, CU 0x7d70ec, DIE 0x91be7a>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/MetaDataStore.cpp:281
#46 0x00000000004bc941 in volumedriverfs::FileSystem::restart_ (this=this@entry=0x7ffce2b0a4b0)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/FileSystem.cpp:416
#47 0x00000000004c6004 in volumedriverfs::FileSystem::FileSystem (this=0x7ffce2b0a4b0, pt=..., registerizle=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/FileSystem.cpp:185
#48 0x0000000000531d3f in volumedriverfs::FuseInterface::FuseInterface (this=0x7ffce2b0a490, pt=..., registerizle=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/FuseInterface.cpp:160
#49 0x00000000004b2b58 in (anonymous namespace)::FileSystemMain::run (this=0x7ffce2b0acf0)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/Main.cpp:256
---Type <return> to continue, or q <return> to quit---
#50 0x0000000000b5dfb2 in youtils::MainHelper::operator() (this=this@entry=0x7ffce2b0acf0)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/youtils/MainHelper.cpp:108
#51 0x00000000004b1fb2 in the_main<(anonymous namespace)::FileSystemMain> (argc=<optimized out>, argv=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-alba-proxy-client-nodelay-release-ubuntu-16.04/volumedriver-core/src/filesystem/../youtils/Main.h:29
#52 0x00007f927e068830 in __libc_start_main (main=0x463c20 <main(int, char**)>, argc=27, argv=0x7ffce2b0b3d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce2b0b3c8)
    at ../csu/libc-start.c:291
```

**Comment by redlicha** [comment]
@JeffreyDevloo , I suggest thawing and addressing this in -ee to prevent unused but snapshotted volumes from getting in the way.

**Comment by redlicha** [comment]
Quick way to check for the issue: look at the tlog sizes in snapshots.xml to see if there are many empty TLogs after the last one with size != 0 (if there is one at all).

**Comment by redlicha** [comment]
ee-6.16.14
