### ISSUE TITLE
Threads performing write hang in rsocket shutdown

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#245]
Voldrv threads are hanging in libibverbs (via librdmacm):
```
(gdb) t 145
[Switching to thread 145 (Thread 0x7f20b6ffd700 (LWP 33501))]
#0  0x00007f227a7d751d in read () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007f227a7d751d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f22748a2d53 in read (__nbytes=8, __buf=0x7f20b6ffbbb0, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  __ibv_get_cq_event (channel=<optimized out>, cq=0x7f20b6ffbbe8, cq_context=0x7f20b6ffbbf0) at src/verbs.c:484
#3  0x00007f2275f5a846 in ?? () from /usr/lib/librdmacm.so.1
#4  0x00007f2275f5c418 in ?? () from /usr/lib/librdmacm.so.1
#5  0x00007f2275f5fdd5 in rshutdown () from /usr/lib/librdmacm.so.1
#6  0x00007f2275f618ea in rclose () from /usr/lib/librdmacm.so.1
#7  0x00000000009108d8 in fungi::Socket::closeNoThrow (this=this@entry=0x7f2025e9d090)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/failovercache/fungilib/Socket.cpp:807
#8  0x00000000009116b7 in fungi::Socket::~Socket (this=0x7f2025e9d090, __in_chrg=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/failovercache/fungilib/Socket.cpp:227
#9  0x0000000000914d27 in fungi::IPv4Socket::~IPv4Socket (this=0x7f2025e9d090, __in_chrg=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/failovercache/fungilib/IPv4Socket.h:32
#10 fungi::IPv4Socket::~IPv4Socket (this=0x7f2025e9d090, __in_chrg=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/failovercache/fungilib/IPv4Socket.h:32
#11 0x00000000008ff3d4 in std::default_delete<fungi::Socket>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:76
#12 std::unique_ptr<fungi::Socket, std::default_delete<fungi::Socket> >::~unique_ptr (this=0x7f2025ec0950, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#13 volumedriver::FailOverCacheProxy::~FailOverCacheProxy (this=0x7f2025ec0950, __in_chrg=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/FailOverCacheProxy.cpp:51
#14 0x0000000000902f7c in std::default_delete<volumedriver::FailOverCacheProxy>::operator() (this=<optimized out>, __ptr=0x7f2025ec0950) at /usr/include/c++/5/bits/unique_ptr.h:76
#15 std::unique_ptr<volumedriver::FailOverCacheProxy, std::default_delete<volumedriver::FailOverCacheProxy> >::reset (__p=0x7f2025ec0950, this=<optimized out>)
    at /usr/include/c++/5/bits/unique_ptr.h:344
#16 std::unique_ptr<volumedriver::FailOverCacheProxy, std::default_delete<volumedriver::FailOverCacheProxy> >::operator=(decltype(nullptr)) (this=<optimized out>)
    at /usr/include/c++/5/bits/unique_ptr.h:280
#17 volumedriver::FailOverCacheSyncBridge::handleException (this=this@entry=0x7f2025e9c580, e=..., where=where@entry=0xdfecc6 "addEntries")
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/FailOverCacheSyncBridge.cpp:242
#18 0x0000000000903da4 in volumedriver::FailOverCacheSyncBridge::addEntries (this=<optimized out>, locs=..., num_locs=<optimized out>, start_address=<optimized out>, 
    data=<optimized out>) at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/FailOverCacheSyncBridge.cpp:141
#19 0x0000000000853614 in volumedriver::Volume::writeClustersToFailOverCache_ (this=this@entry=0x7f2025e9cb90, locs=std::vector of length 4096, capacity 4096 = {...}, 
    num_locs=num_locs@entry=1, start_address=93033792, buf=buf@entry=0x7f1e9c50cd60 "")
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/Volume.cpp:791
#20 0x0000000000859520 in volumedriver::Volume::writeClusters_ (this=this@entry=0x7f2025e9cb90, addr=addr@entry=47633301504, buf=0x7f1e9c50cd60 "", bufsize=bufsize@entry=8192)
[...]
```
4 threads are in that state. Very likely related observation in dmesg:
```
[Fri Jan 27 12:22:42 2017] mlx4_core 0000:81:00.0: CQ overrun on CQN 00066b
[Fri Jan 27 12:22:42 2017] mlx4_core 0000:81:00.1: CQ overrun on CQN 00066b
[Fri Jan 27 12:22:42 2017] mlx4_core 0000:81:00.0: CQ overrun on CQN 0006c0
[Fri Jan 27 12:22:42 2017] mlx4_core 0000:81:00.1: CQ overrun on CQN 0006c0
[Fri Jan 27 12:23:37 2017] mlx4_core 0000:81:00.0: CQ overrun on CQN 00060e
[Fri Jan 27 12:23:37 2017] mlx4_core 0000:81:00.1: CQ overrun on CQN 00060e
[Fri Jan 27 12:23:37 2017] mlx4_core 0000:81:00.0: CQ overrun on CQN 0006c2
[Fri Jan 27 12:23:37 2017] mlx4_core 0000:81:00.1: CQ overrun on CQN 0006c2
```
Related to #220.

**Comment by redlicha** [comment]
```
(gdb) f 17
#17 volumedriver::FailOverCacheSyncBridge::handleException (this=this@entry=0x7f2025f35680, e=..., where=where@entry=0xdfecc6 "addEntries")
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/FailOverCacheSyncBridge.cpp:242
242	/opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/FailOverCacheSyncBridge.cpp: No such file or directory.
(gdb) print *(fungi::IOException*)&e
$4 = {<std::exception> = {<No data fields>}, error_code_ = 0, msg_ = "Socket::wait_for_read request timeout"}
```

**Comment by redlicha** [comment]
```
root@stor-07:~/redlicha/MLNX_OFED_SRC-3.4-1.0.0.0/SOURCES/librdmacm-1.1.0mlnx# dpkg -l librdmacm1
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-======================================================================================
ii  librdmacm1                               1.1.0mlnx-OFED.3.4.0.0.4. amd64                     Userspace RDMA Connection Manager
root@stor-07:~/redlicha/MLNX_OFED_SRC-3.4-1.0.0.0/SOURCES/librdmacm-1.1.0mlnx# dpkg -l libibverbs1
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-======================================================================================
ii  libibverbs1                              1.2.1mlnx1-OFED.3.4.0.1.4 amd64                     Library for direct userspace use of RDMA (InfiniBand/iWARP)
````

**Comment by redlicha** [comment]
```
root@stor-07:~# cat /sys/module/mlx4_core/version 
3.4-1.0.0
root@stor-07:~# for i in $(ls -1 /sys/module/mlx4_core/parameters/*); do echo -n "$i -> "; cat $i; done
/sys/module/mlx4_core/parameters/block_loopback -> 1
/sys/module/mlx4_core/parameters/debug_level -> 0
/sys/module/mlx4_core/parameters/enable_64b_cqe_eqe -> Y
/sys/module/mlx4_core/parameters/enable_qos -> N
/sys/module/mlx4_core/parameters/enable_sys_tune -> 0
/sys/module/mlx4_core/parameters/enable_vfs_qos -> N
/sys/module/mlx4_core/parameters/fast_drop -> 0
/sys/module/mlx4_core/parameters/high_rate_steer -> 0
/sys/module/mlx4_core/parameters/ingress_parser_mode -> 0
/sys/module/mlx4_core/parameters/internal_err_reset -> 1
/sys/module/mlx4_core/parameters/log_mtts_per_seg -> 0
/sys/module/mlx4_core/parameters/log_num_cq -> 16
/sys/module/mlx4_core/parameters/log_num_mac -> 7
/sys/module/mlx4_core/parameters/log_num_mcg -> 13
/sys/module/mlx4_core/parameters/log_num_mgm_entry_size -> -10
/sys/module/mlx4_core/parameters/log_num_mpt -> 19
/sys/module/mlx4_core/parameters/log_num_mtt -> 27
/sys/module/mlx4_core/parameters/log_num_qp -> 19
/sys/module/mlx4_core/parameters/log_num_srq -> 16
/sys/module/mlx4_core/parameters/log_num_vlan -> 0
/sys/module/mlx4_core/parameters/log_rdmarc_per_qp -> 4
/sys/module/mlx4_core/parameters/msi_x -> 1
/sys/module/mlx4_core/parameters/num_vfs -> 1
/sys/module/mlx4_core/parameters/port_type_array -> /sys/module/mlx4_core/parameters/probe_vf -> 1
/sys/module/mlx4_core/parameters/roce_mode -> 2
/sys/module/mlx4_core/parameters/rr_proto -> 254
/sys/module/mlx4_core/parameters/ud_gid_type -> /sys/module/mlx4_core/parameters/use_prio -> N
```

**Comment by redlicha** [comment]
```
root@stor-07:~# for i in $(ls -1 /sys/class/infiniband/mlx4_0/diag_counters/*); do echo -n "$i -> "; cat $i; done
/sys/class/infiniband/mlx4_0/diag_counters/clear_diag -> cat: /sys/class/infiniband/mlx4_0/diag_counters/clear_diag: Permission denied
/sys/class/infiniband/mlx4_0/diag_counters/num_baddb -> 0
/sys/class/infiniband/mlx4_0/diag_counters/num_cqovf -> 4
/sys/class/infiniband/mlx4_0/diag_counters/num_eqovf -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_lae -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_lle -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_lpe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_lqpoe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_mce -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_oos -> 4265
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_rae -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_rire -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_rnr -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_ucsdprd -> 0
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_udsdprd -> 188028
/sys/class/infiniband/mlx4_0/diag_counters/rq_num_wrfe -> 128001588
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_bre -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_lle -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_lpe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_lqpoe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_mwbe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_oos -> 64763
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_rae -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_rire -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_rnr -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_roe -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_rree -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_tree -> 0
/sys/class/infiniband/mlx4_0/diag_counters/sq_num_wrfe -> 436041
```

**Comment by wimpers** [comment]
For BAM: issue with RDMA for the DTL

**Comment by redlicha** [comment]
The librdmacm packages from (M)OFED don't come with debug symbols. Building them manually / loading them (so to be taken with a grain of salt):
```
(gdb) add-symbol-file /usr/lib/debug/usr/lib/librdmacm.so.1.0.0 0x00007f2275f533c0
add symbol table from file "/usr/lib/debug/usr/lib/librdmacm.so.1.0.0" at
	.text_addr = 0x7f2275f533c0
(y or n) y
Reading symbols from /usr/lib/debug/usr/lib/librdmacm.so.1.0.0...done.
(gdb) bt
#0  0x00007f227a7d751d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f22748a2d53 in read (__nbytes=8, __buf=0x7f20b6ffbbb0, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  __ibv_get_cq_event (channel=<optimized out>, cq=cq@entry=0x7f20b6ffbbe8, cq_context=cq_context@entry=0x7f20b6ffbbf0) at src/verbs.c:484
#3  0x00007f2275f5a846 in rs_get_cq_event (rs=rs@entry=0x7f2025ebc940) at src/rsocket.c:1974
#4  0x00007f2275f5c418 in rs_get_cq_event (rs=0x7f2025ebc940) at src/rsocket.c:2029
#5  rs_process_cq (rs=rs@entry=0x7f2025ebc940, nonblock=nonblock@entry=0, test=test@entry=0x7f2275f59140 <rs_conn_all_sends_done>) at src/rsocket.c:2025
#6  0x00007f2275f5fdd5 in rshutdown (socket=<optimized out>, how=how@entry=2) at src/rsocket.c:3242
#7  0x00007f2275f618ea in rclose (socket=<optimized out>) at src/rsocket.c:3281
#8  0x00000000009108d8 in fungi::Socket::closeNoThrow (this=this@entry=0x7f2025e9d090)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/failovercache/fungilib/Socket.cpp:807
[...]
```
```
#3  0x00007f2275f5a846 in rs_get_cq_event (rs=rs@entry=0x7f2025ebc940) at src/rsocket.c:1974
1974		ret = ibv_get_cq_event(rs->cm_id->recv_cq_channel, &cq, &context);
(gdb) print *rs
$1 = {type = 1, index = 363, slock = {sem = {__size = '\000' <repeats 31 times>, __align = 0}, cnt = 0}, rlock = {sem = {__size = '\000' <repeats 31 times>, __align = 0}, cnt = 0}, 
  cq_lock = {sem = {__size = '\000' <repeats 31 times>, __align = 0}, cnt = 0}, cq_wait_lock = {sem = {__size = '\000' <repeats 31 times>, __align = 0}, cnt = 1}, map_lock = {sem = {
      __size = '\000' <repeats 31 times>, __align = 0}, cnt = 0}, {{cm_id = 0x7f2025ec41c0, tcp_opts = 0, keepalive_time = 0, ctrl_seqno = 586, ctrl_max_seqno = 589, sseq_no = 54675, 
      sseq_comp = 55047, rseq_no = 45895, rseq_comp = 46016, remote_sge = 0, remote_sgl = {addr = 140065867095920, key = 3087775541, length = 2}, remote_iomap = {addr = 140065867095952, 
        key = 3087775541, length = 0}, target_mr = 0x7f2025e9d1b0, target_sge = 1, target_iomap_size = 0, target_buffer_list = 0x7f2025ec62b0, target_sgl = 0x7f2025ec62b0, 
      target_iomap = 0x0, rbuf_msg_index = 0, rbuf_bytes_avail = 52508, rbuf_free_offset = 0, rbuf_offset = 52508, rmr = 0x7f2025ec6e10, rbuf = 0x7f2025eea2a0 "\a", 
      sbuf_bytes_avail = 129000, smr = 0x7f2025ebc0d0, ssgl = {{addr = 139776051993884, length = 2072, lkey = 1208715834}, {addr = 139776051946128, length = 508, lkey = 1208715834}}}, {
      qp_list = 0x7f2025ec41c0, dest_map = 0x0, conn_dest = 0x24a00000000, udp_sock = 589, epfd = -687352429, rqe_avail = -1279216825, smsg_free = 0x7f63a040df70}}, opts = 0, 
  fd_flags = 2048, so_opts = 0, ipv6_opts = 0, optval = 0x0, optlen = 0, state = 256, cq_armed = 1, retries = 0, err = 0, sqe_avail = 379, sbuf_size = 131072, sq_size = 384, 
  sq_inline = 88, rbuf_size = 131072, rq_size = 384, rmsg_head = 166, rmsg_tail = 166, {rmsg = 0x7f2025ec9680, dmsg = 0x7f2025ec9680}, sbuf = 0x7f2025eca290 "", remote_iomappings = 0x0, 
  iomap_list = {next = 0x7f2025ebcb40, prev = 0x7f2025ebcb40}, iomap_queue = {next = 0x7f2025ebcb50, prev = 0x7f2025ebcb50}, iomap_pending = 0, unack_cqe = 294}
```

**Comment by wimpers** [comment]
Closing down as there are no plans to support RDMA atm.
