### ISSUE TITLE
Regression in pickle support of SnapshotInfo, VolumeInfo etc.

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#264]
```
arne@blackadder:~/Projects/openvstorage/dev/volumedriver-core$ PATH=target/rtchecked/bin:$PATH PYTHONPATH=target/rtchecked/lib/python2.7/dist-packages:$PYTHONPATH nosetests target/rtchecked/build/filesystem-python-client/test
.EEE.................
======================================================================
ERROR: test_SnapshotInfoPickling (fs_python_client_test.PicklingPythonClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arne/Projects/openvstorage/dev/volumedriver-core/target/rtchecked/build/filesystem-python-client/test/fs_python_client_test.py", line 51, in test_SnapshotInfoPickling
    snapshot_info2 = pickle.loads(dump)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
RuntimeError: unrecognized XML syntax
[...]
```

**Comment by redlicha** [comment]
Above test passes again:
```
arne@blackadder:~/Projects/openvstorage/dev/volumedriver-core$ PATH=target/rtchecked/bin:$PATH PYTHONPATH=target/rtchecked/lib/python2.7/dist-packages:$PYTHONPATH nosetests target/rtchecked/build/filesystem-pyth
on-client/test
.....................
----------------------------------------------------------------------
Ran 21 tests in 0.136s

OK
```
