### ISSUE TITLE
VolumeDriver process terminates with SIGABRT when shutting down with open connections

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#266]
```
[...]
Feb 10 03:32:29 stor-01.be-g8-3 volumedriver_fs.sh[24554]: 2017-02-10 03:32:29 145936 +0100 - stor-01.be-g8-3 - 24554/0x00007f9995ffb700 - volumedriverfs/RocksLogger - 000000000000a082 - info - /mnt/ssd3/vmstor_
db_mds_2: EVENT_LOG_v1 {"time_micros": 1486693949145929, "job": 106, "event": "flush_started", "num_memtables": 1, "num_entries": 61440, "num_deletes": 0, "memory_usage": 19018864}
Feb 10 03:32:30 stor-01.be-g8-3 systemd[1]: Stopping Open vStorage StorageDriver...
Feb 10 03:32:32 stor-01.be-g8-3 volumedriver_fs.sh[24554]: 2017-02-10 03:32:32 639995 +0100 - stor-01.be-g8-3 - 24554/0x00007f9aa5e64700 - volumedriverfs/NetworkXioIOHandler - 000000000000a2ad - error - handle_o
pen: failed to open volume 'volumes/volume_1630' (Failure "chunk 0 failed")
Feb 10 03:32:32 stor-01.be-g8-3 volumedriver_fs.sh[24554]: 2017-02-10 03:32:32 640115 +0100 - stor-01.be-g8-3 - 24554/0x00007f995fff5700 - volumedriverfs/BackendConnectionInterfaceLogger - 000000000000a2ae - inf
o - Logger: Entering write_tag c0b3cac0-db6e-47c4-8ff9-d057d4cb1e7d owner_tag
Feb 10 03:33:00 stor-01.be-g8-3 systemd[1]: ovs-volumedriver_vmstor.service: State 'stop-sigterm' timed out. Killing.
Feb 10 03:33:00 stor-01.be-g8-3 systemd[1]: ovs-volumedriver_vmstor.service: Main process exited, code=killed, status=6/ABRT
Feb 10 03:33:00 stor-01.be-g8-3 systemd[1]: Stopped Open vStorage StorageDriver.
Feb 10 03:33:00 stor-01.be-g8-3 systemd[1]: ovs-volumedriver_vmstor.service: Unit entered failed state.
Feb 10 03:33:00 stor-01.be-g8-3 systemd[1]: ovs-volumedriver_vmstor.service: Failed with result 'signal'.
```

Core dump is not helpful:
```
[...]
[New LWP 32346]
[New LWP 32875]
[New LWP 32877]
[New LWP 32880]
Cannot access memory at address 0x7f909da81148
Cannot access memory at address 0x7f909da81140
Failed to read a valid object file image from memory.
Core was generated by `volumedriver_fs -f --config arakoon://config/ovs/vpools/234f3386-39e6-4ec2-99e6'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f90978ad418 in ?? ()
[Current thread is 1 (LWP 38097)]
(gdb) bt
#0  0x00007f90978ad418 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7f8fb4995b68
```

**Comment by redlicha** [comment]
Possibly related?: inspection of core dumps after voldrv crashes (log files were unfortunately gone already) where certain threads (`NetworkXio*`, `FuseInterface`, ...) are *absent*: 
[s04-gdb-bt.txt](https://github.com/openvstorage/volumedriver/files/773510/s04-gdb-bt.txt)

**Comment by redlicha** [comment]
Truncated core dumps: the shutdown in the systemd unit files first tries a `fusermount -u`, waits for a bit and then first tries a `SIGTERM` and finally a `SIGKILL`. If the `SIGKILL` arrives while the core dump is written the core dump is not completed:
```
Feb 16 00:58:28 stor-02 systemd[1]: Stopping Open vStorage StorageDriver...
[...]
Feb 16 00:58:58 stor-02 systemd[1]: ovs-volumedriver_data04.service: State 'stop-sigterm' timed out. Killing.
Feb 16 00:58:58 stor-02 systemd[1]: ovs-volumedriver_data04.service: Main process exited, code=killed, status=6/ABRT
Feb 16 00:58:58 stor-02 systemd[1]: Stopped Open vStorage StorageDriver.
Feb 16 00:58:58 stor-02 systemd[1]: ovs-volumedriver_data04.service: Unit entered failed state.
Feb 16 00:58:58 stor-02 systemd[1]: ovs-volumedriver_data04.service: Failed with result 'signal'.
```

**Comment by redlicha** [comment]
Hypothesis after further inspection of the core dumps: `api::Exit` was not invoked as `VolManager::instance_ != nullptr` (and its member threads, e..g `PeriodicActions`, Backend threadpool etc are the remaining active threads) -> `volumedriverfs::LocalNode` dtor did not run.

**Comment by redlicha** [comment]
Logging for one occasion of the bug shows a problem in the `LocalNode` ctor: if anything throws after the `api::Init` call, `api::Exit` is not invoked leading to the above symptoms. It's unclear if this is the only occasion.

**Comment by redlicha** [comment]
Another occasion of the bug, different trigger:
* a volume failover is ongoing in a `NetworkXioWorkQueue` thread, which runs into problems connecting to MDS(es) (they're being shut down at the same time) => keeps `LocalNode` alive:
```
[...]
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 238920 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/MDSMetaDataStore - 000000000000638d - error - do_failover_: a5ca8
b83-20ee-458c-b882-06f20ac0f057: failover to mds://10.109.3.44:26300 failed: Operation canceled
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 238950 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/MDSMetaDataStore - 000000000000638e - info - build_new_one_: a5ca
8b83-20ee-458c-b882-06f20ac0f057: attempting failover to mds://10.109.3.41:26300
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 238960 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/MDSMetaDataStore - 000000000000638f - info - connect_: a5ca8b83-20ee-458c-b882-06f20ac0f057: connecting to mds://10.109.3.41:26300
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 239289 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/LocORemClientHelpers - 0000000000006390 - info - is_local: 10.109.3.41 does not appear to be a local address
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 239474 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/LocORemClientHelpers - 0000000000006391 - info - operator(): 10.109.3.41:26300: connected
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 239504 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/LocORemConnection - 0000000000006392 - info - LocORemConnection: 0x7f9208007550: new connection 10.109.3.42:47762 (local) <-> 10.109.3.41:26300 (remote)
Feb 16 00:58:21 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:21 239613 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/MetaDataServerClientNG - 0000000000006393 - info - ClientNG: 0x7f92080044c0: mds://10.109.3.41:26300, shmem size 65536, is local: false, timeout: 20 secs
[...]
* voldrv is asked to shut down:
```
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 121739 +0100 - stor-02.be-g8-4 - 12149/0x00007f9293fff700 - volumedriverfs/FuseInterface - 00000000000063c3 - info - run_: fuse loop exited
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 121982 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/FuseInterface - 00000000000063c4 - info - operator(): stopping network (xio) server
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 122605 +0100 - stor-02.be-g8-4 - 12149/0x00007f9303331700 - volumedriverfs/SignalThread - 00000000000063c5 - info - operator(): caught signal 15
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 122645 +0100 - stor-02.be-g8-4 - 12149/0x00007f9303331700 - volumedriverfs/FuseInterface - 00000000000063c6 - info - operator(): caught signal 15
```
* at this point the `NetworkXioWorkQueue` thread is still active, and a new `ZWorker` is also spawned:

Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 134449 +0100 - stor-02.be-g8-4 - 12149/0x00007f929bfff700 - volumedriverfs/ZWorker - 00000000000063c7 - info - create_socket_: 1: connecting socket to pool inproc://ObjectRouterWorkerPool-back
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 134567 +0100 - stor-02.be-g8-4 - 12149/0x00007f92f77fe700 - volumedriverfs/ZWorker - 00000000000063c8 - info - ZWorker: 1: up and running
[...]
```
* shutdown proceeds:
```
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 159918 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/FuseInterface - 00000000000063cb - info - operator(): waiting for network (xio) thread to finish
[...]
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 161821 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/FileSystem - 00000000000063d2 - info - ~FileSystem: e4e08853-236b-4894-8c3d-c8652e5baa9c: sayonara
[...]
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 162338 +0100 - stor-02.be-g8-4 - 12149/0x00007f92f6ffd700 - volumedriverfs/PeriodicAction - 00000000000063d6 - info - run: StatsCollector: exiting
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 162769 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/VFSObjectRouter - 00000000000063d7 - info - ~ObjectRouter: Bye
```
* eventually the failover fails (no MDS available), and the ZWorker also exits, but at this point the `at_exit` message shows that the main thread is exiting:
```
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 413530 +0100 - stor-02.be-g8-4 - 12149/0x00007f929b7fe700 - volumedriverfs/VFSObjectRouter - 000000000000646d - error - steal_: a5ca8b83-20ee-458c-b882-06f20ac0f057: failed to restart: All failover attempts failed - giving up
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 413822 +0100 - stor-02.be-g8-4 - 12149/0x00007f929bfff700 - volumedriverfs/ZWorker - 000000000000646e - info - do_work_: 1: termination requested
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 413821 +0100 - stor-02.be-g8-4 - 12149/0x00007f92f77fe700 - volumedriverfs/ZWorkerPool - 000000000000646f - info - route_: ObjectRouterWorkerPool: stop requested, breaking out of the loop
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 413872 +0100 - stor-02.be-g8-4 - 12149/0x00007f92fd661700 - volumedriverfs/PeriodicAction - 0000000000006470 - info - run: ScrubManager: exiting
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 414058 +0100 - stor-02.be-g8-4 - 12149/0x00007f92927fc700 - volumedriverfs/VolManager - 0000000000006471 - info - stop: Stopping the Volume Manager: should only happen on shutdown
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 414087 +0100 - stor-02.be-g8-4 - 12149/0x00007f92927fc700 - volumedriverfs/VolManager - 0000000000006472 - info - stop: Cleaning up 14 components.
[...]
at_exit: Time spent executing user instructions (seconds): 163.560000
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 414691 +0100 - stor-02.be-g8-4 - 12149/0x00007f930cccb700 - volumedriverfs/PeriodicAction - 0000000000006478 - info - run: MetaDataFreeSpaceChecker: exiting
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 414883 +0100 - stor-02.be-g8-4 - 12149/0x00007f92fe663700 - volumedriverfs/PeriodicAction - 0000000000006479 - info - run: FailOverCacheChecker: exiting
Feb 16 00:58:41 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:41 414988 +0100 - stor-02.be-g8-4 - 12149/0x00007f92927fc700 - volumedriverfs/VolManager - 000000000000647a - info - ~VolManager: stopping thread pool
```

**Comment by redlicha** [comment]
```
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 121982 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/FuseInterface - 00000000000063c4 - info - operator(): stopping network (xio) server
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.134192] xio_task.h:331               [ERROR] - tasks inventory: 822/824 = missing:2
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.134238] xio_task.c:342               [ERROR] - pool_name:ctx:0x7f92a8009670 - primary_pool_tcp: in use: task:0x7f92a98a3480, type:0x12
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.134244] xio_task.c:342               [ERROR] - pool_name:ctx:0x7f92a8009670 - primary_pool_tcp: in use: task:0x7f92a98b43b8, type:0x12
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.159830] xio_idr.c:176                [ERROR] - user object leaked: 0x7f92a9303a30, type:struct xio_session
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.159854] xio_idr.c:176                [ERROR] - user object leaked: 0x7f92a99448e0, type:struct xio_connection
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.159859] xio_idr.c:176                [ERROR] - user object leaked: 0x7f92a99446b0, type:struct xio_session
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: [2017/02/16-00:58:28.159865] xio_idr.c:176                [ERROR] - user object leaked: 0x7f92a9303c50, type:struct xio_connection
Feb 16 00:58:28 stor-02 volumedriver_fs.sh[12149]: 2017-02-16 00:58:28 159918 +0100 - stor-02.be-g8-4 - 12149/0x00007f93e68e3900 - volumedriverfs/FuseInterface - 00000000000063cb - info - operator(): waiting for network (xio) thread to finish
```
`NetworkXioIOHandler` is attached as "user context" to the xio connection which keeps the `NetworkXioWorkQueue`(s) alive (via `shared_ptr`s). The `NetworkXioWorkQueue` thread driving the failover keeps in turn the `LocalNode` alive, also via a `shared_ptr`, so it can outlive the `ObjectRouter` / `FileSystem`. In fact, `ObjectRouter`s dtor runs while the failover in the WQ thread still uses it.

**Comment by wimpers** [comment]
Closed by PM.
