### ISSUE TITLE
`MDSClient.create_namespace` times out

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#286]
Observed in https://github.com/openvstorage/framework/issues/1530 :
```
Mar 16 12:25:27 ovs04 celery[116189]: Traceback (most recent call last):
Mar 16 12:25:27 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 989, in remove_storagedriver
Mar 16 12:25:27 ovs04 celery[116189]:     excluded_storagerouters=[storage_router] + storage_routers_offline)
Mar 16 12:25:27 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 621, in ensure_safety
Mar 16 12:25:27 ovs04 celery[116189]:     client.create_namespace(str(vdisk.volume_id))
Mar 16 12:25:27 ovs04 celery[116189]: RuntimeError: Operation canceled
```

**Comment by redlicha** [comment]
Probably caused by slow operation(s) - `set_role` waiting for the backend sync job to finish - blocking the thread(s) . This can also impact the data path, so the slow operations need to be moved out.

**Comment by wimpers** [comment]
Closed by PM.
