### ISSUE TITLE
fuse, voldrv and albaproxy crashed while removing volumes in bulk

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/volumedriver#69]
While deleting the volumes in bulk, the voldrv and albaproxy process crashed due to a failure of fuse.

DMESG
```
[Thu Jul 14 03:01:20 2016] init: ovs-volumedriver_vpool7 main process (41548) killed by ABRT signal
[Thu Jul 14 03:01:20 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:21 2016] show_signal_msg: 1 callbacks suppressed
[Thu Jul 14 03:01:21 2016] volumedriver_fs[59264]: segfault at f1 ip 000000000056b7ee sp 00007fff2ea3b9a0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process (59264) killed by SEGV signal
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:21 2016] volumedriver_fs[59466]: segfault at f1 ip 000000000056b7ee sp 00007ffc37543d60 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process (59466) killed by SEGV signal
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:21 2016] volumedriver_fs[59698]: segfault at f1 ip 000000000056b7ee sp 00007ffcf40808d0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process (59698) killed by SEGV signal
[Thu Jul 14 03:01:21 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:21 2016] volumedriver_fs[59962]: segfault at f1 ip 000000000056b7ee sp 00007ffc964cb510 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process (59962) killed by SEGV signal
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:22 2016] volumedriver_fs[60154]: segfault at f1 ip 000000000056b7ee sp 00007ffdb0180fc0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process (60154) killed by SEGV signal
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:22 2016] volumedriver_fs[60357]: segfault at f1 ip 000000000056b7ee sp 00007ffca0f1c5d0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process (60357) killed by SEGV signal
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:22 2016] volumedriver_fs[60558]: segfault at f1 ip 000000000056b7ee sp 00007ffcad4268a0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process (60558) killed by SEGV signal
[Thu Jul 14 03:01:22 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:23 2016] volumedriver_fs[60765]: segfault at f1 ip 000000000056b7ee sp 00007fff58b2be20 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 main process (60765) killed by SEGV signal
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:23 2016] volumedriver_fs[60999]: segfault at f1 ip 000000000056b7ee sp 00007ffcc636ea10 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 main process (60999) killed by SEGV signal
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 main process ended, respawning
[Thu Jul 14 03:01:23 2016] volumedriver_fs[61336]: segfault at f1 ip 000000000056b7ee sp 00007ffe534eabf0 error 4 in volumedriver_fs[400000+aa2000]
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 main process (61336) killed by SEGV signal
[Thu Jul 14 03:01:23 2016] init: ovs-volumedriver_vpool7 respawning too fast, stopped
[Thu Jul 14 03:05:06 2016] sched: RT throttling activated
```

Crashdump voldrv
```
ProcStatus:
 Name:  volumedriver_fs
 State: D (disk sleep)
 Tgid:  56776
 Ngid:  0
 Pid:   56776
 PPid:  1
 TracerPid:     0
 Uid:   0       0       0       0
 Gid:   0       0       0       0
 FDSize:        512
 Groups:        0 
 NStgid:        56776
 NSpid: 56776
 NSpgid:        56776
 NSsid: 56776
 VmPeak:        17223960 kB
 VmSize:        15978704 kB
 VmLck:        0 kB
 VmPin:    17072 kB
 VmHWM:  2694500 kB
 VmRSS:   698916 kB
 VmData:        15782812 kB
 VmStk:      136 kB
 VmExe:    10888 kB
 VmLib:    25480 kB
 VmPTE:     3596 kB
 VmPMD:       80 kB
 VmSwap:               0 kB
 Threads:       258
 SigQ:  1/1030220
 SigPnd:        0000000000000000
 ShdPnd:        0000000000000000
 SigBlk:        0000000000004001
 SigIgn:        0000000000001000
 SigCgt:        0000000180004003
 CapInh:        0000000000000000
 CapPrm:        0000003fffffffff
 CapEff:        0000003fffffffff
 CapBnd:        0000003fffffffff
 Seccomp:       0
 Cpus_allowed:  ff,ffffffff,ffffffff
 Cpus_allowed_list:     0-71
 Mems_allowed:  00000000,00000003
 Mems_allowed_list:     0-1
 voluntary_ctxt_switches:       121
 nonvoluntary_ctxt_switches:    912
Signal: 6
Uname: Linux 4.2.0-42-generic x86_64
UserGroups: 
CoreDump: base64
```

Debugtool
```
#0  0x00007fd5c00d6c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fd5c00da028 in __GI_abort () at abort.c:89
#2  0x00007fd5c0a1078d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fd5c0a0e7f6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fd5c0a0e841 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fd5c0a0e856 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fd5c0a0e4b2 in __cxa_call_unexpected () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000000000053e657 in volumedriverfs::FuseInterface::route_to_fs_instance_<std::unique_ptr<volumedriverfs::Handle, std::default_delete<volumedriverfs::Handle> > > (mem_fun=
(void (volumedriverfs::FileSystem::*)(volumedriverfs::FileSystem * const, const volumedriverfs::FrontendPath &, std::unique_ptr<volumedriverfs::Handle, std::default_delete<volumedriverfs::Handle> >)) 0x4d6c10 <volumedriverfs::FileSystem::releasedir(volumedriverfs::FrontendPath const&, std::unique_ptr<volumedriverfs::Handle, std::default_delete<volumedriverfs::Handle> >)>, frontend_path=frontend_path@entry=0x0)
at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/FuseInterface.cpp:403
#8  0x0000000000534a48 in volumedriverfs::FuseInterface::releasedir (path=0x0, fi=0x7fd4117f9ab0)
at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-dev-release-ubuntu-14.04/volumedriver-core/src/filesystem/FuseInterface.cpp:456
#9  0x0000000000a8efcd in fuse_lib_releasedir (req=0x7fd3fc024660, ino=47, llfi=<optimized out>) at ../../fuse-master-4600e52e831d05e31fc54e666ff729bcab054017.git/lib/fuse.c:3644
#10 0x0000000000a95559 in do_releasedir (req=<optimized out>, nodeid=<optimized out>, inarg=<optimized out>)
at ../../fuse-master-4600e52e831d05e31fc54e666ff729bcab054017.git/lib/fuse_lowlevel.c:1532
#11 0x0000000000a97e8
```

**Comment by redlicha** [comment]
Duplicates #67. However, albaproxy crashes are not explained by this - please open a separate ticket for alba for htese.
